### ISSUE TITLE
Replace deprecated plugin gatsby-plugin-prefetch-google-fonts

### ISSUE THREAD

**Issue by LayaTaal** [Arts-Matter/gatsby-site#42]
Gatsby throws the following error: `"gatsby-plugin-prefetch-google-fonts" threw an error while running the onPreBootstrap lifecycle:
ENOENT: no such file or directory, stat '.cache/google-fonts//fonts'`.

See: https://github.com/gatsbyjs/gatsby/issues/27607

**Comment by fono97** [comment]
I think that plugin is no longer supported 
you should use this instead  run npm install "gatsby-plugin-google-fonts"
